- name: Setup Master Node for Control Plate
  hosts: master
  become: true
  tasks:
    - name: Reset Kubernetes component
      ansible.builtin.command: "kubeadm reset --force"
      failed_when: false
      changed_when: true

    - name: Create an empty file for Kubeadm configuring
      ansible.builtin.copy:
        content: ""
        dest: /etc/kubernetes/kubeadm-config.yaml
        force: false
        mode: ""

    - name: Configuring the container runtime including its cgroup driver
      ansible.builtin.blockinfile:
        path: /etc/kubernetes/kubeadm-config.yaml
        block: |
             kind: ClusterConfiguration
             apiVersion: kubeadm.k8s.io/v1beta3
             networking:
               podSubnet: "10.244.0.0/16"
             ---
             kind: KubeletConfiguration
             apiVersion: kubelet.config.k8s.io/v1beta1
             runtimeRequestTimeout: "15m"
             cgroupDriver: "systemd"
             systemReserved:
               cpu: 100m
               memory: 350M
             kubeReserved:
               cpu: 100m
               memory: 50M
             enforceNodeAllocatable:
             - pods

    - name: Initialize the cluster (this could take some time)
      ansible.builtin.command: |
        kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
      changed_when: false

    - name: Create .kube directory
      become: true
      ansible.builtin.file:
        path: /home/ansible/.kube
        state: directory
        mode: "0755"

    - name: Copy admin.conf to user's kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ansible/.kube/config
        remote_src: true
        mode: "0600"
        owner: ansible

    - name: Install Pod network
      become: true
      become_user: ansible
      ansible.builtin.shell: |
        kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      args:
        chdir: /home/ansible
        creates: pod_network_setup.log
