---
- name: Reset Kubernetes
  hosts: master, worker
  gather_facts: false
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  vars:
    container_runtime: containerd
  tasks:
    - name: Reset Kubernetes component
      ansible.builtin.command:
        cmd: "kubeadm reset --force"
      ignore_errors: true
      register: my_output
      changed_when: my_output.rc != 0
    - name: Delete /etc/cni/
      ansible.builtin.file:
        state: absent
        path: /etc/cni/net.d/
    - name: Delete /opt/cni/bin
      ansible.builtin.file:
        state: absent
        path: '{{ item }}'
      with_items:
        - /etc/cni/net.d/flannel
        - /etc/cni/net.d/calico-ipam
        - /etc/cni/net.d/calico
    - name: Find network interfaces for Kubernetes
      ansible.builtin.command:
        cmd: "ip addr | grep {{ item }}"
      with_items:
        - "docker0"
        - "flannel.1"
        - "cni0"
        - "tunl0"
      register: find_eths
      ignore_errors: true
    - name: Delete network interfaces for Kubernetes
      when: item.stdout != ''
      ansible.builtin.command:
        cmd: "ip link delete {{ item.item }}"
      with_items: "{{ find_eths['results'] }}"
    - name: Find blackhole route rule
      ansible.builtin.command:
        cmd: "ip route | awk '/blackhole/ {print $2}'"
      register: find_blackhole
      ignore_errors: true
    - name: Delete blackhole route rule
      when: find_blackhole.stdout != ''
      ansible.builtin.command: 
        cmd: "ip route del {{ find_blackhole.stdout }}"
      ignore_errors: true