---
# https://opensourcegeeks.net/how-to-automate-a-kubernetes-cluster-setup-with-ansible/
- name: Play for install k8s
  hosts: all
  remote_user: ansible
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  gather_facts: true
  connection: ssh
  tasks:
    - name: Create containerd config file
      ansible.builtin.file:
        path: "/etc/modules-load.d/containerd.conf"
        state: "touch"
        mode: '0644'

    - name: Add config for containerd
      ansible.builtin.blockinfile:
        path: "/etc/modules-load.d/containerd.conf"
        block: |
          overlay
          br_netfilter

    - name: Add module overlay with modprobe 
      community.general.modprobe:
        name: overlay
        state: present
    
    - name: Add module overlay with modprobe 
      community.general.modprobe:
        name: br_netfilter
        state: present
    
    - name: Set system configs for Kubernetes networking
      ansible.builtin.file:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        state: "touch"
        mode: '0644'

    - name: Add config for containerd
      blockinfile:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        block: |
              net.bridge.bridge-nf-call-iptables = 1
              net.ipv4.ip_forward = 1
              net.bridge.bridge-nf-call-ip6tables = 1

    - name: Apply new settings
      command: sudo sysctl --system

    - name: Install containerd
      shell: |
        sudo apt-get update && sudo apt-get install -y containerd
        sudo mkdir -p /etc/containerd
        sudo containerd config default | sudo tee /etc/containerd/config.toml
        sudo systemctl restart containerd
    
    - name: Make the Swap inactive
      command: swapoff -a
    
    - name: Remove Swap entry from /etc/fstab.
      lineinfile:
        dest: /etc/fstab
        regexp: swap
        state: absent
    
    - name: Installing Prerequisites for Kubernetes
      apt: 
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - vim
          - software-properties-common
          - nfs-common
        state: present
    
    - name: Add Google official GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    
    - name: Add Kubernetes Repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main 
        state: present
        filename: kubernetes
        mode: 0600
    
    - name: Installing Kubernetes Cluster Packages.
      apt: 
        name:
          - kubeadm=1.27.6-00
          - kubectl=1.27.6-00
          - kubelet=1.27.6-00
        state: present
        force: true
    
    - name: Apt Hold kubernetes
      shell: |
        apt-mark hold kubelet kubeadm kubectl
    
    - name: Enable service kubelet, and enable persistently
      service: 
        name: kubelet
        enabled: true
    
    - name: Reboot all the kubernetes nodes.
      reboot:
        post_reboot_delay: 10
        reboot_timeout: 60
        connect_timeout: 90
        test_command: uptime
...
