---
- name: Setup master node
  hosts: master
  remote_user: ansible
  gather_facts: true
  connection: ssh
  vars:
    # the Pod Network CIDR, example: 192.168.100.0/24
    pod_network_cidr: 10.244.0.0/16
    # the Apiserver advertise address
    k8s_master_ip: "master01"
    # the Pod network manifest file URL, Your choice could be flannel, weave or calico, etc.
    pod_network_manifest_file: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
  tasks:
    - name: Intilizing Kubernetes Cluster
      become: true
      become_method: ansible.builtin.sudo
      become_user: root
      ansible.builtin.shell: |
       kubeadm init --pod-network-cidr "{{ pod_network_cidr }}"
      run_once: true
      delegate_to: "{{ k8s_master_ip }}"
    - name: Pause 30 seconds
      ansible.builtin.pause:
        seconds: 30
    - name: Create directory for kube config.
      become: true
      ansible.builtin.file:
        path: /home/{{ ansible_ssh_user }}/.kube
        state: directory
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: "0755"
    - name: Copy /etc/kubernetes/admin.conf to user's home directory ~/.kube/config.
      become_user: root
      become_method: ansible.builtin.sudo
      become: true
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_ssh_user }}/.kube/config
        remote_src: true
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: '0644'
    - name: Pause 10 seconds
      ansible.builtin.pause:
        seconds: 10
    - name: Remove the cache directory.
      become_method: ansible.builtin.sudo
      become: true
      ansible.builtin.file:
        path: /home/{{ ansible_ssh_user }}/.kube/cache
        state: absent
    - name: Create Pod Network & RBAC.
      command: "{{ item }}"
      with_items:
        - kubectl apply -f {{ pod_network_manifest_file }}

    - name: Pause 20 seconds
      ansible.builtin.pause:
        seconds: 20

    - name: Get the token for joining the nodes with Kuberentes master.
      become_user: root
      become_method: ansible.builtin.sudo
      become: true
      ansible.builtin.command:
        cmd: kubeadm token create  --print-join-command
      register: kubernetes_join_command
    - name: Print kubernetes_join_command
      ansible.builtin.debug:
        msg: "{{ kubernetes_join_command.stdout }}"

- name: Copy join command to local file.
  hosts: localhost
  tasks:
    - name: Copy join command to local file.
      ansible.builtin.copy:
        content: "{{ hostvars['master01']['kubernetes_join_command']['stdout_lines'][0] }}"
        dest: "/tmp/kubernetes_join_command"
        mode: "0777"
...
