---
- name: Setup worker nodes
  hosts: worker
  gather_facts: true
  connection: ssh
  remote_user: ansible
  tasks:
   - name: Copy join command to worker nodes.
     become: true
     become_method: ansible.builtin.sudo
     become_user: root
     ansible.builtin.copy:
      src: /tmp/kubernetes_join_command
      dest: /tmp/kubernetes_join_command
      mode: "0777"
   
   - name: Join the Worker nodes with the master.
     become: true
     become_method: ansible.builtin.sudo
     become_user: root
     ansible.builtin.command:
      cmd: sh /tmp/kubernetes_join_command
     register: joined_or_not
   
   - name: Print kubernetes_join_command
     ansible.builtin.debug:
      msg: "{{ joined_or_not.stdout }}"

- name: Add label for workers
  hosts: localhost
  tasks:
   - name: Configure worker.
     ansible.builtin.command:
      cmd: kubectl label nodes --selector="kubernetes.io/hostname!=master01" "kubernetes.io/role=worker"
...
