---
- name: Setup NFS
  hosts: nfs
  gather_facts: true
  connection: ssh
  remote_user: ansible
  tasks:
    - name: Print disk info
      become: true
      become_user: root
      shell: "fdisk -l | grep -i 'Disk /dev/' "
      register: command_output
    - name: Print disk info
      ansible.builtin.debug:
        var: command_output.stdout_lines
    - name: Install nfs-kernel-server
      become: true
      become_user: root
      become_method: ansible.builtin.sudo
      ansible.builtin.apt:
        name:
          - nfs-kernel-server
    - name: Create NFS dir
      become: true
      become_user: root
      become_method: ansible.builtin.sudo
      ansible.builtin.file:
        path: /k8s_nfs
        state: directory
        recurse: true
        mode: "0777"
    - name: Check if couchbase.host is already defined
      become: true
      become_user: root
      become_method: ansible.builtin.sudo
      lineinfile:
        state: absent
        path: "/etc/exports"
        regexp: "^/k8s_nfs"
      check_mode: true
      changed_when: false # This just makes things look prettier in the logs
      register: check


    - name: Setup export folder
      become: true
      become_user: root
      become_method: ansible.builtin.sudo
      ansible.builtin.lineinfile:
        path: "/etc/exports"
        line: '/k8s_nfs  192.168.0.0/16(rw,sync,no_subtree_check)'
        state: present
      when: check.found == 0

    - name: Enable NFS export
      become: true
      become_user: root
      become_method: ansible.builtin.sudo
      ansible.builtin.command:
        cmd: exportfs -ra
    
    - name: Enable NFS service
      become: true
      become_user: root
      become_method: ansible.builtin.sudo
      ansible.builtin.systemd:
        name: nfs-kernel-server
        state: reloaded

    - name: Check if couchbase.host is already defined
      become: true
      become_user: root
      become_method: ansible.builtin.sudo
      ansible.builtin.command:
        cmd: showmount -e
      register: export_check
    
    - debug:
       var: export_check.stdout_lines

