apiVersion: v1
kind: Service
metadata:
  name: airbyte-airbyte-webapp-svc # Sets service name
  namespace: airbyte
  labels:
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: webapp
    app.kubernetes.io/version: 0.50.31
    helm.sh/chart: webapp-0.49.4
spec:
  type: ClusterIP # Sets service type
  ports:
    - port: 80 # Sets port to run the postgres application
      name: http
  selector:
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/name: webapp
