- name: Setup longhorn
  hosts: localhost
  tasks:
    - name: Add longhorn repository
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io
    - name: Deploy longhorn chart using values files on target
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        create_namespace: true
        values_files:
          - longhorn-values.yml
        binary_path: /opt/homebrew/bin/helm

    - name: Apply Ingress policy for homer to the cluster.
      kubernetes.core.k8s:
        state: present
        force: true
        definition:
          apiVersion: v1
          data:
            tls.crt: "{{ lookup('template', '/Users/pengtan/Downloads/learn-data.dev-ssl/star_learn-data_dev.pem') | b64encode }}"
            tls.key: "{{ lookup('template', '/Users/pengtan/Downloads/learn-data.dev-ssl/star_learn-data_dev.key') | b64encode }}"
          kind: Secret
          metadata:
            name: ingress-cert
            namespace: longhorn-system
          type: kubernetes.io/tls

    - name: Apply Ingress policy for longhorn to the cluster.
      kubernetes.core.k8s:
        state: present
        src: longhorn-ingress.yml
