- name: Helm uninstall superset
  hosts: localhost
  tasks:
    - name: Deploy superset chart using values files on target
      kubernetes.core.helm:
        name: superset
        release_namespace: superset
        binary_path: /opt/homebrew/bin/helm
        release_state: absent
        wait: true

    - name: Delete superset namespace
      kubernetes.core.k8s:
        name: superset
        api_version: v1
        kind: Namespace
        state: absent
        wait: true
