---
- hosts: localhost
  tasks: 
  - name: Create local directory
    file:
      path: /home/pengtan/.kube/
      state: directory
    delegate_to: localhost

- hosts: master
  remote_user: ansible
  gather_facts: yes
  connection: ssh
  tasks:
  - name: Copy /etc/kubernetes/admin.conf to user's home directory /home/{{ ansible_user }}/.kube/config.
    fetch: 
      src: /home/{{ ansible_user }}/.kube/config 
      dest: /home/pengtan/.kube/
      fail_on_missing: True
      flat: yes