- name: Helm install kube-prometheus-stack
  hosts: localhost
  vars:
    app_name: kube-prometheus-stack
    app_namespace: kube-prometheus-stack
  tasks:
    - name: Add repository {{ app_name }}
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts

    - name: Deploy chart using values files on target for {{ app_name }}
      kubernetes.core.helm:
        name: "{{ app_name }}"
        chart_ref: "prometheus-community/{{ app_name }}"
        release_namespace: "{{ app_namespace }}"
        values_files:
          - "{{ app_name }}-values.yml"
        binary_path: /opt/homebrew/bin/helm
        create_namespace: true

    - name: Create tls secret to the cluster for {{ app_name }}
      kubernetes.core.k8s:
        state: present
        force: true
        definition:
          apiVersion: v1
          data:
            tls.crt: "{{ lookup('template', '/Users/pengtan/Downloads/learn-data.dev-ssl/star_learn-data_dev.pem') | b64encode }}"
            tls.key: "{{ lookup('template', '/Users/pengtan/Downloads/learn-data.dev-ssl/star_learn-data_dev.key') | b64encode }}"
          kind: Secret
          metadata:
            name: ingress-cert
            namespace: "{{ app_namespace }}"
          type: kubernetes.io/tls

    - name: Apply Ingress policy to the cluster for airbyte
      kubernetes.core.k8s:
        state: present
        src: "{{ app_name }}-ingress.yml"
