- name: Helm uninstall airflow
  hosts: localhost
  tasks:
    - name: Deploy airflow chart using values files on target
      kubernetes.core.helm:
        name: airflow
        release_namespace: airflow
        binary_path: /opt/homebrew/bin/helm
        release_state: absent
        wait: true

    - name: Delete airflow namespace
      kubernetes.core.k8s:
        name: airflow
        api_version: v1
        kind: Namespace
        state: absent
        wait: true
