- name: Helm install argocd
  hosts: localhost
  tasks:
    - name: Add argocd repository
      kubernetes.core.helm_repository:
        name: argocd
        repo_url: https://argoproj.github.io/argo-helm

    - name: Deploy argocd chart using values files on target
      kubernetes.core.helm:
        name: argocd
        chart_ref: argocd/argo-cd
        release_namespace: argocd
        values_files:
          - argocd-values.yml
        binary_path: /opt/homebrew/bin/helm
        create_namespace: true

    - name: Apply Ingress policy for argocd to the cluster.
      kubernetes.core.k8s:
        state: present
        src: argocd-ingress.yml
