- name: Helm uninstall postgresql
  hosts: localhost
  tasks:
    - name: Deploy postgresql chart using values files on target
      kubernetes.core.helm:
        name: postgresql
        release_namespace: postgresql
        binary_path: /opt/homebrew/bin/helm
        release_state: absent
        wait: true

    - name: Delete postgresql namespace
      kubernetes.core.k8s:
        name: postgresql
        api_version: v1
        kind: Namespace
        state: absent
        wait: true
