- name: Helm uninstall prometheus
  hosts: localhost
  tasks:
    - name: Deploy prometheus chart using values files on target
      kubernetes.core.helm:
        name: prometheus
        release_namespace: prometheus
        binary_path: /opt/homebrew/bin/helm
        release_state: absent
        wait: true

    - name: Delete prometheus namespace
      kubernetes.core.k8s:
        name: prometheus
        api_version: v1
        kind: Namespace
        state: absent
        wait: true
