- name: Setup prometheus
  hosts: localhost
  tasks:
    - name: Add kube-prometheus-stack repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts

    - name: Deploy prometheus chart using values files on target
      kubernetes.core.helm:
        name: kube-prometheus-stack
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: prometheus
        create_namespace: true
        values_files:
          - prometheus-values.yaml
        binary_path: /opt/homebrew/bin/helm

    - name: Apply Ingress policy for prometheus to the cluster.
      kubernetes.core.k8s:
        state: present
        src: prometheus-ingress.yml
