apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: prometheus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: prometheus.master01.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-exporter-prometheus-server
            port: 
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-redirect
  namespace: prometheus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "https://prometheus.master01.test"
spec:
  ingressClassName: nginx
  rules:
  - host: master01.test
    http:
      paths:
      - path: /prometheus
        pathType: Prefix
        backend:
          service:
            name: node-exporter-prometheus-server
            port: 
              number: 80