- name: Helm install homer
  hosts: localhost
  tasks:
    - name: Add homer repository
      kubernetes.core.helm_repository:
        name: djjudas21
        repo_url: https://djjudas21.github.io/charts/

    - name: Deploy homer chart using values files on target
      kubernetes.core.helm:
        name: homer
        chart_ref: djjudas21/homer
        release_namespace: homer
        values_files:
          - homer-values.yml
        binary_path: /opt/homebrew/bin/helm
        create_namespace: true
    - name: Apply Ingress policy for homer to the cluster.
      kubernetes.core.k8s:
        state: present
        src: homer-ingress.yml
