- name: Helm install homer
  hosts: localhost
  vars:
    namespace: homer
    name: homer
  tasks:
    - name: Add homer repository
      kubernetes.core.helm_repository:
        name: djjudas21
        repo_url: https://djjudas21.github.io/charts/

    - name: Uninstall homer chart using values files on target
      kubernetes.core.helm:
        name: "{{ name }}"
        chart_ref: djjudas21/homer
        release_namespace: "{{ namespace }}"
        binary_path: /opt/homebrew/bin/helm
        create_namespace: true
        state: absent

    - name: Deploy homer chart using values files on target
      kubernetes.core.helm:
        name: "{{ name }}"
        chart_ref: djjudas21/homer
        release_namespace: "{{ namespace }}"
        values_files:
          - homer-values.yml
        binary_path: /opt/homebrew/bin/helm
        create_namespace: true

    - name: Apply Ingress policy for homer to the cluster.
      kubernetes.core.k8s:
        state: present
        force: true
        definition:
          apiVersion: v1
          data:
            tls.crt: "{{ lookup('template', '/Users/pengtan/Downloads/learn-data.dev-ssl/star_learn-data_dev.pem') | b64encode }}"
            tls.key: "{{ lookup('template', '/Users/pengtan/Downloads/learn-data.dev-ssl/star_learn-data_dev.key') | b64encode }}"
          kind: Secret
          metadata:
            name: ingress-cert
            namespace: "{{ namespace }}"
          type: kubernetes.io/tls


    - name: Apply Ingress policy for homer to the cluster.
      kubernetes.core.k8s:
        state: present
        src: homer-ingress.yml
