---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Learn-data.dev dashboard"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: false
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Learn-data.dev dashboard"
  icon: "fa fa-grin"
  content: "This is the homepage of Learn-data.dev."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/NUSTemple/cluster-init-setup"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  - name: "Google"
    icon: "fa-brands fa-google"
    url: "https://www.google.com.sg/" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Code Development"
    icon: "fas terminal"
    items:
      - name: "VSCode"
        logo: "https://raw.githubusercontent.com/NUSTemple/cluster-init-setup/master/src/kubernetes-app/coder-server/coder-server-logo.png"
        subtitle: "Code Server"
        tag: "app"
        keywords: "self hosted code server"
        url: "https://code.learn-data.dev/"
        target: "_blank" # optional html a tag target attribute
  - name: "Data Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Airflow"
        logo: "https://airflow.apache.org/docs/apache-airflow/2.3.3/_images/pin_large.png"
        subtitle: "Airflow for data workflow"
        tag: "app"
        keywords: "self hosted airflow"
        url: "https://airflow.learn-data.dev/"
        target: "_blank" # optional html a tag target attribute
      - name: "Airbyte"
        logo: "https://seeklogo.com/images/A/airbyte-logo-CC005A0105-seeklogo.com.png"
        subtitle: "Another application"
        tag: "app"
        url: "https://airbyte.learn-data.dev/"
        target: "_blank" 
      - name: "Datahub"
        logo: "https://content.linkedin.com/content/dam/engineering/site-assets/images/blog/posts/2019/08/datahublogo.png"
        subtitle: "Datahub for data metadata"
        tag: "app"
        url: "https://datahub.learn-data.dev/"
        target: "_blank" 
      - name: "Superset"
        logo: "https://www.know-bi.be/hubfs/42724554.png"
        subtitle: "Superset BI Dashboard"
        tag: "app"
        url: "https://superset.learn-data.dev/"
        target: "_blank"
      - name: "Doris"
        logo: "https://www.datanami.com/wp-content/uploads/2022/06/ApacheDoris.png"
        subtitle: "Doris DB"
        tag: "app"
        url: "https://doris.learn-data.dev/"
        target: "_blank"
      - name: "Postgres"
        logo: "https://cdn.icon-icons.com/icons2/2415/PNG/512/postgresql_plain_wordmark_logo_icon_146390.png"
        subtitle: "Postgres DB"
        tag: "app"
        url: "https://pg.learn-data.dev/"
        target: "_blank"
  - name: "Cluster Monitoring"
    icon: "fa-solid fa-chart-simple"
    items:
      - name: "Kuboard"
        logo: "https://cdn4.iconfinder.com/data/icons/logos-brands-5/24/kubernetes-512.png"
        subtitle: "Cluster dashboard"
        tag: "cluster"
        keywords: "self hosted Longhorn"
        url: "https://kuboard.learn-data.dev/"
        target: "_blank"
      - name: "Grafana"
        logo: "https://cdn.icon-icons.com/icons2/2699/PNG/512/grafana_logo_icon_171048.png"
        subtitle: "Grafana dashboard"
        tag: "monitoring"
        keywords: "self hosted Grafana"
        url: "https://grafana.learn-data.dev/"
        target: "_blank" # optional html a tag target attribute
      - name: "Longhorn"
        logo: "https://longhorn.io/img/logos/longhorn-icon-color.png"
        subtitle: "Longhorn dashboard"
        tag: "storage"
        keywords: "self hosted Longhorn"
        url: "https://longhorn.learn-data.dev/"
        target: "_blank"
      - name: "Prometheus"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/2066px-Prometheus_software_logo.svg.png"
        subtitle: "Longhorn dashboard"
        tag: "monitoring"
        keywords: "self hosted Longhorn"
        url: "https://longhorn.learn-data.dev/"
        target: "_blank"