- name: Helm uninstall wordpress
  hosts: localhost
  tasks:
    - name: Deploy wordpress chart using values files on target
      kubernetes.core.helm:
        name: wordpress
        release_namespace: wordpress
        binary_path: /opt/homebrew/bin/helm
        release_state: absent
        wait: true

    - name: Delete wordpress namespace
      kubernetes.core.k8s:
        name: wordpress
        api_version: v1
        kind: Namespace
        state: absent
        wait: true
