apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-data
  namespace: planka
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi