- name: Helm install metrics-server
  hosts: localhost
  tasks:
    - name: Add metrics-server  repository
      kubernetes.core.helm_repository:
        name: metrics-server
        repo_url: https://kubernetes-sigs.github.io/metrics-server/

    - name: Deploy metrics-server chart using values files on target
      kubernetes.core.helm:
        name: metrics-server
        chart_ref: metrics-server/metrics-server
        release_namespace: metrics-server
        values_files:
          - metrics-server-values.yml
        binary_path: /opt/homebrew/bin/helm
        create_namespace: true
