- name: Setup phpmyadmin
  hosts: localhost
  vars:
    app_namespace: phpmyadmin
    app_name: phpmyadmin
  tasks:
    - name: Deploy phpmyadmin chart using values files on target
      kubernetes.core.helm:
        name: phpmyadmin
        chart_ref: oci://registry-1.docker.io/bitnamicharts/phpmyadmin
        release_namespace: phpmyadmin
        create_namespace: true
        values_files:
          - phpmyadmin-values.yml
        binary_path: /opt/homebrew/bin/helm

    - name: Create tls secret to the cluster for {{ app_name }}
      kubernetes.core.k8s:
        state: present
        force: true
        definition:
          apiVersion: v1
          data:
            tls.crt: "{{ lookup('template', '/Users/pengtan/Downloads/learn-data.dev-ssl/star_learn-data_dev.pem') | b64encode }}"
            tls.key: "{{ lookup('template', '/Users/pengtan/Downloads/learn-data.dev-ssl/star_learn-data_dev.key') | b64encode }}"
          kind: Secret
          metadata:
            name: ingress-cert
            namespace: "{{ app_namespace }}"
          type: kubernetes.io/tls

    - name: Deploy Ingress to the cluster for {{ app_name }}
      kubernetes.core.k8s:
        state: present
        src: "{{ app_name }}-ingress.yml"
