- name: Helm install airbyte
  hosts: localhost
  vars:
    app_name: airbyte
    app_namespace: airbyte
  tasks:
    - name: Add repository {{ app_name }}
      kubernetes.core.helm_repository:
        name: "{{ app_name }}"
        repo_url: https://airbytehq.github.io/helm-charts

    - name: Deploy airbyte chart using values files on target
      kubernetes.core.helm:
        name: "{{ app_name }}"
        chart_ref: airbyte/airbyte
        release_namespace: "{{ app_namespace }}"
        values_files:
          - "{{ app_name }}-values.yaml"
        binary_path: /opt/homebrew/bin/helm
        create_namespace: true

    - name: Create tls secret to the cluster for {{ app_name }}
      kubernetes.core.k8s:
        state: present
        force: true
        definition:
          apiVersion: v1
          data:
            tls.crt: "{{ lookup('template', '/Users/pengtan/Downloads/learn-data.dev-ssl/star_learn-data_dev.pem') | b64encode }}"
            tls.key: "{{ lookup('template', '/Users/pengtan/Downloads/learn-data.dev-ssl/star_learn-data_dev.key') | b64encode }}"
          kind: Secret
          metadata:
            name: ingress-cert
            namespace: "{{ app_namespace }}"
          type: kubernetes.io/tls

    - name: Apply Ingress policy to the cluster for airbyte
      kubernetes.core.k8s:
        state: present
        src: "{{ app_name }}-ingress.yml"
