---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  namespace: datahub
data:
  postgres-password: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-secrets
  namespace: datahub
data:
  neo4j-password: ZGF0YWh1YnBhc3N3b3Jk


