---
- hosts: all
  tasks:
  - name: Check the disk
    become: true
    become_user: root
    shell: "fdisk -l | grep -i 'Disk /dev/' "
    register: command_output

  - debug:
      var: command_output.stdout_lines