---
- name: Install Node Dependencies
  hosts: all
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
         - inxi
         - htop
         - tree
         - vim
         - nano
         - neofetch