- name: Setup rook-ceph
  hosts: localhost
  tasks:
    - name: Add rook-ceph repository
      kubernetes.core.helm_repository:
        name: rook-release
        repo_url: https://charts.rook.io/release

    - name: Deploy rook-ceph chart using values files on target
      kubernetes.core.helm:
        name: rook-release
        chart_ref: rook-release/rook-ceph
        release_namespace: rook-ceph
        create_namespace: true
        values_files:
          - rook-ceph-values.yml
        binary_path: /opt/homebrew/bin/helm

    - name: Apply yml to create rook-ceph cluster.
      kubernetes.core.k8s:
        state: present
        src: rook-ceph-cluster.yml

    - name: Apply yml to create rook-ceph sc.
      kubernetes.core.k8s:
        state: present
        src: rook-ceph-storageclass.yml

    - name: Apply multiple patch operations to an existing Pod
      kubernetes.core.k8s:
        api_version: storage.k8s.io/v1
        kind: StorageClass
        state: present
        name: rook-ceph-block
        definition: |
          metadata:
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"

    - name: Apply Ingress policy for prometheus to the cluster.
      kubernetes.core.k8s:
        state: present
        src: rook-ceph-ingress.yml
