- name: Kubectl install Doris Custom Resource Definition(CRD)
  hosts: localhost
  tasks:
    - name: Deploy doris CRD
      kubernetes.core.k8s:
        state: present
        src: doris.selectdb.com_dorisclusters.yml

    - name: Deploy doris operator
      kubernetes.core.k8s:
        state: present
        src: operator.yml

    - name: Deploy Doris Cluster.
      kubernetes.core.k8s:
        state: present
        src: doriscluster-values.yml

    - name: Apply Ingress policy for doris to the cluster.
      kubernetes.core.k8s:
        state: present
        src: doris-ingress.yml
